# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from helpermodules.utils.error_handling import ImportErrorContext
with ImportErrorContext():
    from google.protobuf import descriptor as _descriptor
    from google.protobuf import descriptor_pool as _descriptor_pool
    from google.protobuf import symbol_database as _symbol_database
    from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvehicle.proto\"\x81\x01\n\nNewRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\'\n\x06\x63onfig\x18\x03 \x03(\x0b\x32\x17.NewRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1e\n\x08NewReply\x12\x12\n\nvehicle_id\x18\x01 \x01(\x03\"/\n\nSoCRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nvehicle_id\x18\x02 \x01(\x03\"\x17\n\x08SoCReply\x12\x0b\n\x03soc\x18\x01 \x01(\x01\x32K\n\x07Vehicle\x12\x1f\n\x03New\x12\x0b.NewRequest\x1a\t.NewReply\"\x00\x12\x1f\n\x03SoC\x12\x0b.SoCRequest\x1a\t.SoCReply\"\x00\x42\nZ\x08proto/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010proto/pb'
  _globals['_NEWREQUEST_CONFIGENTRY']._options = None
  _globals['_NEWREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_NEWREQUEST']._serialized_start=18
  _globals['_NEWREQUEST']._serialized_end=147
  _globals['_NEWREQUEST_CONFIGENTRY']._serialized_start=102
  _globals['_NEWREQUEST_CONFIGENTRY']._serialized_end=147
  _globals['_NEWREPLY']._serialized_start=149
  _globals['_NEWREPLY']._serialized_end=179
  _globals['_SOCREQUEST']._serialized_start=181
  _globals['_SOCREQUEST']._serialized_end=228
  _globals['_SOCREPLY']._serialized_start=230
  _globals['_SOCREPLY']._serialized_end=253
  _globals['_VEHICLE']._serialized_start=255
  _globals['_VEHICLE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
