import pytest


@pytest.fixture()
def regular_daily_log_entry_processed_legacy_converted():
    return {'entries': [{'bat': {'all': {'energy_exported': 0,
                                         'energy_imported': 0,
                                         'exported': 3195.13,
                                         'fault_state': 0,
                                         'imported': 629.37,
                                         'power_average': 0,
                                         'power_exported': 0,
                                         'power_imported': 0,
                                         'soc': 48},
                                 'bat2': {'energy_exported': 0,
                                          'energy_imported': 0,
                                          'exported': 3195.13,
                                          'fault_state': 0,
                                          'imported': 629.37,
                                          'power_average': 0,
                                          'power_exported': 0,
                                          'power_imported': 0,
                                          'soc': 48}},
                         'counter': {'counter0': {'energy_exported': 0.772,
                                                  'energy_imported': 0,
                                                  'exported': 26029.945,
                                                  'fault_state': 0,
                                                  'grid': True,
                                                  'imported': 2728.572,
                                                  'power_average': -9.3,
                                                  'power_exported': 9.3,
                                                  'power_imported': 0}},
                         'cp': {'all': {'energy_exported': 0,
                                        'energy_imported': 0,
                                        'energy_imported_bat': 0,
                                        'energy_imported_cp': 0,
                                        'energy_imported_grid': 0,
                                        'energy_imported_pv': 0,
                                        'exported': 0,
                                        'fault_state': 0,
                                        'imported': 12639.11,
                                        'power_average': 0,
                                        'power_exported': 0,
                                        'power_imported': 0},
                                'cp3': {'energy_exported': 0,
                                        'energy_imported': 0,
                                        'energy_imported_bat': 0,
                                        'energy_imported_cp': 0,
                                        'energy_imported_grid': 0,
                                        'energy_imported_pv': 0,
                                        'exported': 0,
                                        'fault_state': 0,
                                        'imported': 12639.11,
                                        'power_average': 0,
                                        'power_exported': 0,
                                        'power_imported': 0},
                                'cp4': {'energy_exported': 0,
                                        'energy_imported': 0,
                                        'energy_imported_bat': 0,
                                        'energy_imported_cp': 0,
                                        'energy_imported_grid': 0,
                                        'energy_imported_pv': 0,
                                        'exported': 0,
                                        'fault_state': 0,
                                        'imported': 0,
                                        'power_average': 0,
                                        'power_exported': 0,
                                        'power_imported': 0},
                                'cp5': {'energy_exported': 0,
                                        'energy_imported': 0,
                                        'energy_imported_bat': 0,
                                        'energy_imported_cp': 0,
                                        'energy_imported_grid': 0,
                                        'energy_imported_pv': 0,
                                        'exported': 0,
                                        'fault_state': 0,
                                        'imported': 0,
                                        'power_average': 0,
                                        'power_exported': 0,
                                        'power_imported': 0}},
                         'date': '14:25',
                         'energy_source': {'bat': 0.0, 'cp': 0.0, 'grid': 0.0, 'pv': 1.0},
                         'ev': {'ev0': {'soc': None}},
                         'hc': {'all': {'energy_exported': 0,
                                        'energy_imported': 0.037,
                                        'energy_imported_bat': 0,
                                        'energy_imported_cp': 0,
                                        'energy_imported_grid': 0,
                                        'energy_imported_pv': 0.037,
                                        'fault_state': 0,
                                        'imported': 2324.001611140539,
                                        'power_average': 0.448,
                                        'power_exported': 0,
                                        'power_imported': 0.448}},
                         'prices': {'bat': 0.0002, 'grid': 0.0003, 'pv': 0.00015},
                         'pv': {'all': {'energy_exported': 0.809,
                                        'energy_imported': 0,
                                        'exported': 35827,
                                        'fault_state': 0,
                                        'power_average': -9.74,
                                        'power_exported': 9.74,
                                        'power_imported': 0},
                                'pv1': {'energy_exported': 0.809,
                                        'energy_imported': 0,
                                        'exported': 35827,
                                        'fault_state': 0,
                                        'power_average': -9.74,
                                        'power_exported': 9.74,
                                        'power_imported': 0}},
                         'sh': {},
                         'timestamp': 1750767902}],
            'message': '',
            'names': {'bat2': 'MQTT-Speicher',
                      'counter0': 'MQTT-Zähler',
                      'counter2': 'Test-Zähler',
                      'cp3': 'MQTT-Ladepunkt',
                      'cp4': 'MQTT-Ladepunkt',
                      'cp5': 'MQTT-Ladepunkt',
                      'ev0': 'Standard-Fahrzeug',
                      'pv1': 'MQTT-Wechselrichter'},
            'totals': {'bat': {'all': {'energy_exported': 0, 'energy_imported': 0},
                               'bat2': {'energy_exported': 0, 'energy_imported': 0}},
                       'counter': {'counter0': {'energy_exported': 772.41,
                                                'energy_imported': 0,
                                                'grid': True}},
                       'cp': {'all': {'energy_exported': 0,
                                      'energy_imported': 0,
                                      'energy_imported_bat': 0,
                                      'energy_imported_cp': 0,
                                      'energy_imported_grid': 0,
                                      'energy_imported_pv': 0},
                              'cp3': {'energy_exported': 0,
                                      'energy_imported': 0,
                                      'energy_imported_bat': 0,
                                      'energy_imported_cp': 0,
                                      'energy_imported_grid': 0,
                                      'energy_imported_pv': 0},
                              'cp4': {'energy_exported': 0,
                                      'energy_imported': 0,
                                      'energy_imported_bat': 0,
                                      'energy_imported_cp': 0,
                                      'energy_imported_grid': 0,
                                      'energy_imported_pv': 0},
                              'cp5': {'energy_exported': 0,
                                      'energy_imported': 0,
                                      'energy_imported_bat': 0,
                                      'energy_imported_cp': 0,
                                      'energy_imported_grid': 0,
                                      'energy_imported_pv': 0}},
                       'hc': {'all': {'energy_imported': 37.177,
                                      'energy_imported_bat': 0,
                                      'energy_imported_cp': 0,
                                      'energy_imported_grid': 0,
                                      'energy_imported_pv': 37.177}},
                       'pv': {'all': {'energy_exported': 809},
                              'pv1': {'energy_exported': 809}},
                       'sh': {}}}
