name: Build Web Theme Colors

on:
  push:
    paths:
      - packages/modules/web_themes/colors/source/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: packages/modules/web_themes/colors/source/package-lock.json

      - name: Install Dependencies and Build
        run: |
          cd packages/modules/web_themes/colors/source
          npm install
          npm run build --if-present

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add packages/modules/web_themes/colors/web
          if ! git diff --cached --quiet; then
            git commit -m "Build Web Theme: Colors"
            git push
          else
            echo "No changes to commit."
          fi
