name: Node.js CI

on:
  push:
    paths:
      - packages/modules/web_themes/koala/source/**
    branches:
      - main
  pull_request:
    paths:
      - packages/modules/web_themes/koala/source/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 22, 24 ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: packages/modules/web_themes/koala/source/package-lock.json

      - name: Install Dependencies and Build
        run: |
          cd packages/modules/web_themes/koala/source
          npm install
          npm run lint
          npm run test:unit
          npm run build --if-present
